spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flyway?useSSL=false&serverTimezone=CTT&allowPublicKeyRetrieval=true
    username: root
    password: root

# 数据库版本控制
  flyway:
    enabled: true # 开启 Flyway 功能
    clean-disabled: true # 禁用 Flyway 所有的 drop 相关的逻辑，避免出现跑路的情况
    table: example_flyway_schema_history # 自定义flyway版本记录表名称 默认表名: flyway_schema_history
    out-of-order: true # 是否加载遗漏的老版本 开发环境可以开启 生产环境应该关闭
    locations: # 迁移脚本目录
      - classpath:db/migration
      - classpath:com/toma/framework/lab01databaseversioncontrolflyway/migration
    check-location: false  # 是否校验迁移脚本目录下。如果配置为 true ，代表需要校验。此时，如果目录下没有迁移脚本，会抛出 IllegalStateException 异常
    url: jdbc:mysql://localhost:3306/flyway?useSSL=false&useUnicode=true&characterEncoding=UTF-8 # 数据库地址
    user: root # 数据库账号
    password: root # 数据库密码

    baseline-version: 0 #当不是一个空数据库的时候 开启
    baseline-on-migrate: true  #当不是一个空数据库的时候 开启