flow:
  nodes: # 名称节点
    node:
      - id: a  # 节点自定义的名称
        calss: com.toma.framework.lab05liteflow.component.ACmp # 节点包名全限定名称
      - id: b
        class: com.toma.framework.lab05liteflow.component.BCmp
      - id: c
        class: com.toma.framework.lab05liteflow.component.CCmp
      - id: d
        class: com.toma.framework.lab05liteflow.component.DCmp
  chain:
    - name: chain1 # 命名节点
      condition: # 执行条件
        - type: then # then 同步流程
          value: 'a,b,c,d' # 执行节点
    - name: chain2
      condition:
        - type: then
          value: 'a,b'
        - type: then
          value: 'c,d'
    - name: chainSync1 # 异步执行
      condition:
        - type: when
          value: 'a,b,c,d' #表示4个组件会并行的执行
    - name: chainSyncGroup1 # 异步并行组
      condition:
        - group: 'g1' # 分组名称
          type: when
          value: 'a,b' # 分组执行组件节点
          errorResume: false # 当前组出线异常 不执行下一异常组
        - group: 'g2' # 分组名称
          type: when
          value: 'c,d' # 分组执行组件节点

    - name: chainOneEnd # 异步任意线程结束继续
      condition:
        - type: pre # 流程开始前执行 节点
          value: 'a,b'
        - type: finally # 后置节点 流程结束后 一定会执行 不受异常影响
          value: 'd'
        - type: when # 这个是异步执行 全部执行完成才会执行 下面的 d组件
          value: 'c,b'
          any: true # 只要 c/b 组件任意一个执行完成 便会执行下面的 d组件
        - type: then
          value: 'd'
        - type: then
          value: 'b,c,switch(a|d)' # 动态的业务逻辑进行选择下一执行节点
        - type: then
          value: 'a[第一个标签]'

